version: '3.3'
services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        volumes:
            - db-data:/var/lib/postgresql/data/ 
        ports:
            - "6666:5432"
    app:
        env_file: 
            - .env
        build: 
            context: .
            args:
                USER_ID: ${USER_ID:-0}
                GROUP_ID: ${GROUP_ID:-0}
        ports:
            - "80:80"
        volumes:
            - .:/app
        depends_on:
            - db
        
volumes:
    db-data:
